name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build and Package APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease

       - name: Upload APK to Telegram
        uses: appleboy/telegram-upload@v2
        with:
          files: ./app/build/outputs/apk/release/app-release.apk
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          caption: |
            又又又更新代码了，真是勤劳的一天
            
            GitHub New CI
            
            `${{ github.event.head_commit.message }}`
            
            by `${{ github.event.head_commit.author.name }}`
            
            See commit detail [here](${{ github.event.head_commit.url }})
        run: |
          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage -d chat_id=${TELEGRAM_CHAT_ID} -d text=${COMMIT_MESSAGE}
          
        
          
